project:
  type: website

website:
  title: "rstd.io/build-quarto-blog"
  navbar:
    pinned: true
    left:
      - text: "Introduction"
        file: intro.qmd
      - text: "Recap"
        file: recap.qmd
      - text: "Let's build a blog with Quarto"
        file: lets-build-a-quarto-blog/index.qmd
      - text: "Workflows"
        file: workflow.qmd
      - text: "Learn more"
        file: learn-more.qmd
    right:
      - icon: github
        href: https://github.com/ivelasq/2022-08-30_building-a-blog-with-quarto
    page-navigation: true

format:
  html:
    theme: [litera, styles.scss]
    css: styles.scss
    highlight-style: tango

editor: source

